version: '3.1'

services:
  db:
    image: mysql:8.0.31
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: ContainerTesisDB
    volumes:
      - ./dbdata:/var/lib/mysql

    
